# Generated by Django 5.0.3 on 2024-03-29 20:05

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0003_rename_student_studentenrollment_student_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('manager', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(default='123456', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(default='123456', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_reg_number',
            field=models.CharField(default='1234567', max_length=20),
        ),
    ]
