# Generated by Django 5.0.3 on 2024-03-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0004_alter_customuser_managers_customuser_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examofficerassignment',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='examofficerassignment',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='supervisorassignment',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='supervisorassignment',
            name='job_title',
        ),
        migrations.AlterField(
            model_name='examofficerassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheduler.department'),
        ),
        migrations.AlterField(
            model_name='examofficerassignment',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sheduler.exam'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sheduler.course'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sheduler.department'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='matric',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisorassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheduler.department'),
        ),
        migrations.AlterField(
            model_name='supervisorassignment',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sheduler.exam'),
        ),
    ]
