# Generated by Django 5.0.3 on 2024-04-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0009_alter_examofficerassignment_employee_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamOfficerAssignment',
            new_name='ExamOfficerProfile',
        ),
        migrations.RenameModel(
            old_name='StudentEnrollment',
            new_name='StudentProfile',
        ),
        migrations.RenameModel(
            old_name='SupervisorAssignment',
            new_name='SupervisorProfile',
        ),
    ]
