# Generated by Django 5.0.3 on 2024-04-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0013_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('exam_officer', 'Exam_Officer')], default='student', max_length=20),
        ),
    ]
