# Generated by Django 5.0.3 on 2024-05-26 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0016_remove_course_end_date_remove_course_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='deapartment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='sheduler.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='sheduler.faculty'),
        ),
        migrations.CreateModel(
            name='RegisteredCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sheduler.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sheduler.studentprofile')),
            ],
        ),
    ]
