# Generated by Django 5.0.3 on 2024-05-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0017_remove_studentprofile_course_course_deapartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='deapartment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='faculty',
        ),
    ]
