# Generated by Django 5.0.3 on 2024-05-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0020_rename_student_name_studentprofile_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examofficerprofile',
            old_name='exam_officer_name',
            new_name='exam_officer',
        ),
        migrations.RenameField(
            model_name='supervisorprofile',
            old_name='supervisor_name',
            new_name='supervisor',
        ),
    ]
