# Generated by Django 5.0.3 on 2024-05-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0021_rename_exam_officer_name_examofficerprofile_exam_officer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='matric',
            new_name='matriculated',
        ),
    ]
