# Generated by Django 5.0.3 on 2024-05-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0022_rename_matric_studentprofile_matriculated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamSchedule',
            new_name='Exam',
        ),
        migrations.RemoveField(
            model_name='examofficerprofile',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='exam',
        ),
    ]
