# Generated by Django 5.0.3 on 2024-05-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0023_rename_examschedule_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='matriculated',
            field=models.BooleanField(default=False),
        ),
    ]
