# Generated by Django 5.0.3 on 2024-05-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0024_alter_studentprofile_matriculated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='deapartment',
            new_name='department',
        ),
    ]
