# Generated by Django 5.0.3 on 2024-05-26 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0027_alter_exam_exam_officer_alter_exam_supervisors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exams_assigned', to='sheduler.examofficerprofile'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='supervisors',
            field=models.ManyToManyField(related_name='exams_supervised', to='sheduler.supervisorprofile'),
        ),
        migrations.AlterField(
            model_name='examattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
