# Generated by Django 5.0.3 on 2024-05-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0028_alter_exam_exam_officer_alter_exam_supervisors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcourses',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
