# Generated by Django 5.0.3 on 2024-05-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0032_alter_examattendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredcourses',
            name='attended',
        ),
    ]
