# Generated by Django 5.0.3 on 2024-05-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0033_remove_registeredcourses_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='teken',
            field=models.BooleanField(default=False),
        ),
    ]
