# Generated by Django 5.0.3 on 2024-05-28 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0034_exam_teken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='exam/material')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheduler.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamReevaluationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheduler.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheduler.studentprofile')),
            ],
        ),
    ]
