# Generated by Django 5.0.3 on 2024-05-28 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0035_exammaterial_examreevaluationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
