# Generated by Django 5.0.3 on 2024-06-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0036_alter_studentprofile_student'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
