# Generated by Django 5.0.3 on 2024-06-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0038_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='NO CODE YET', max_length=255),
        ),
    ]
