# Generated by Django 5.0.3 on 2024-06-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0039_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
